### ISSUE TITLE
JsonQuantityReader Annotation is not available during runtime

### ISSUE THREAD

**Issue by simon-schneider-gcx** [raynigon/unit-api#72]
**Describe the bug**
JsonQuantityReader Annotation is broken and not covered by test cases.

**To Reproduce**
1. use the `JsonQuantityReader`
2. It will not work

**Expected behavior**
```
@Target({METHOD, FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface JsonQuantityReader {
```

**Additional context**

**Comment by raynigon** [comment]
Fixed with 65fe4eef83c7b8e5ee2c3e1affcfde232a227af4
